### ISSUE TITLE
Custom subclasses does not work

### ISSUE THREAD

**Issue by FoxWorn3365** [microsievert/SubclassMod#1]
**Version:** `v3.0.0` (https://github.com/microsievert/SubclassMod/releases/tag/3.0.0)
**EXILED Version:** `v8.1.0`

**Bug**
> The __automatic__ spawn of subclasses at the beginning of the round does not work despite the fact that the possibilities given in `subclass_chance` and `spawn_percent` are at 100 but work with the `force` command.

**Config:**
```yml
subclass_mod:
  is_enabled: true
  debug: true
  # Replace roleplay names for class d to number identificators
  class_d_numbers: true
  # Chance to get subclass instead of overwritten role
  subclass_chance: 100
  # Time while that will be shown spawn info broadcast after spawn
  spawn_broadcast_time: 10
  # First names for human classes
  human_first_names: []
  human_special_signs: []
  # Additional info for roles
  custom_roles_info:
    Scientist:
    # Prefix that will be placed before nickname
      name_prefix: 'Dr. '
      # Postfix that will be placed after nickname
      name_postfix: ''
      # Custom info of overridden role
      custom_info: ''
      # Is inventory overridden
      inventory_overridden: false
      # Naming method for this role
      naming_method: Firstname
      # Overwritten items list
      inventory_overwrite: []
      # Add any EXILED custom items by id
      inventory_custom_items: []
  # List of subclasses for every base role. EVERY new custom subclass start from - (ID'S SHOULD BE UNIQUE)
  custom_subclasses:
  - id: 10
    max_players: 1
    health: 100
    spawn_percent: 100
    name: 'Class D Janitor'
    description: 'Lo zio pera'
    name_prefix: ''
    name_postfix: ''
    custom_info: 'Janitor'
    forceclass_only: false
    base_role: ClassD
    spawn_method: SpawnZone
    naming_method: Signs
    ammo:
      Nato9: 0
      Nato556: 0
      Nato762: 0
    custom_items: []
    items:
    - KeycardJanitor
    spawn_zones:
    - LightContainment
    spawn_rooms: []
    spawn_positions: []
  # List of player's personal custom characters that can be selected by console command
  custom_characters: []
  # List of rooms that won't be selected as player spawn room.
  restricted_spawn_rooms:
  - EzShelter
  - EzCollapsedTunnel
  - EzVent
  - Lcz330
  - Lcz173
  - Lcz914
  - LczArmory
```
